config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/first_task', to: 'welcome#first_task'
  get 'welcome/second_task', to: 'welcome#second_task'
  get 'welcome/third_task', to: 'welcome#third_task'
  get 'welcome/task4', to: 'welcome#task4'
  get 'welcome/task5', to: 'welcome#task5'
  get 'welcome/task6', to: 'welcome#task6'
  get 'welcome/task7', to: 'welcome#task7'
  get 'welcome/task8', to: 'welcome#task8'

  root 'welcome#index'

  resources :orders
  resources :magazines
  resources :authors
  resources :books
  resources :librarians
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, :surname, presence: true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :surname, :country_of_birth, :country_of_death, :year_of_birth, :gender)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :author_name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname, id: :author_surname %>
  </div>

  <div class="field">
    <%= form.label :country_of_birth %>
    <%= form.text_field :country_of_birth, id: :author_country_of_birth %>
  </div>

  <div class="field">
    <%= form.label :country_of_death %>
    <%= form.text_field :country_of_death, id: :author_country_of_death %>
  </div>

  <div class="field">
    <%= form.label :year_of_birth %>
    <%= form.number_field :year_of_birth, id: :author_year_of_birth %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.collection_select :gender, ['male', 'female'], :to_s, :to_s, prompt: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class="container">
  <h1>Editing Author</h1>

  <%= render 'form', author: @author %>

  <%= link_to 'Show', @author %> |
  <%= link_to 'Back', authors_path %>
</div>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>


<table class="table">
  <tr>
    <td><h1>Author</h1></td>
    <td><%= link_to 'New Author', new_author_path, class: 'btn btn-info float-right' %></td>
  </tr>
</table>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Country of birth</th>
      <th>Country of death</th>
      <th>Year of birth</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.surname %></td>
        <td><%= author.country_of_birth %></td>
        <td><%= author.country_of_death %></td>
        <td><%= author.year_of_birth %></td>
        <td><%= author.gender %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="d-flex justify-content-center">
  <%= will_paginate @authors, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/authors/new.html.erb
<div class="container">
  <h1>New Author</h1>

  <%= render 'form', author: @author %>

  <%= link_to 'Back', authors_path %>
</div>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @author.name %>
  </p>

  <p>
    <strong>Surname:</strong>
    <%= @author.surname %>
  </p>

  <p>
    <strong>Country of birth:</strong>
    <%= @author.country_of_birth %>
  </p>

  <p>
    <strong>Country of death:</strong>
    <%= @author.country_of_death %>
  </p>

  <p>
    <strong>Year of birth:</strong>
    <%= @author.year_of_birth %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= @author.gender %>
  </p>

  <%= link_to 'Edit', edit_author_path(@author) %> |
  <%= link_to 'Back', authors_path %>
</div>