config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/first_task', to: 'welcome#first_task'
  get 'welcome/second_task', to: 'welcome#second_task'
  get 'welcome/third_task', to: 'welcome#third_task'
  get 'welcome/task4', to: 'welcome#task4'
  get 'welcome/task5', to: 'welcome#task5'
  get 'welcome/task6', to: 'welcome#task6'
  get 'welcome/task7', to: 'welcome#task7'
  get 'welcome/task8', to: 'welcome#task8'

  root 'welcome#index'

  resources :orders
  resources :magazines
  resources :authors
  resources :books
  resources :librarians
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/magazine.rb
class Magazine < ApplicationRecord
  has_and_belongs_to_many :orders, dependent: :destroy

  validates :name, presence: true
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  before_action :set_magazine, only: [:show, :edit, :update, :destroy]

  # GET /magazines
  # GET /magazines.json
  def index
    @magazines = Magazine.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /magazines/1
  # GET /magazines/1.json
  def show
  end

  # GET /magazines/new
  def new
    @magazine = Magazine.new
  end

  # GET /magazines/1/edit
  def edit
  end

  # POST /magazines
  # POST /magazines.json
  def create
    @magazine = Magazine.new(magazine_params)

    respond_to do |format|
      if @magazine.save
        format.html { redirect_to @magazine, notice: 'Magazine was successfully created.' }
        format.json { render :show, status: :created, location: @magazine }
      else
        format.html { render :new }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazines/1
  # PATCH/PUT /magazines/1.json
  def update
    respond_to do |format|
      if @magazine.update(magazine_params)
        format.html { redirect_to @magazine, notice: 'Magazine was successfully updated.' }
        format.json { render :show, status: :ok, location: @magazine }
      else
        format.html { render :edit }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazines/1
  # DELETE /magazines/1.json
  def destroy
    @magazine.destroy
    respond_to do |format|
      format.html { redirect_to magazines_url, notice: 'Magazine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magazine
      @magazine = Magazine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def magazine_params
      params.require(:magazine).permit(:name, :issue_number)
    end
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/views/magazines/_form.html.erb
<%= form_with(model: magazine, local: true) do |form| %>
  <% if magazine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(magazine.errors.count, "error") %> prohibited this magazine from being saved:</h2>

      <ul>
      <% magazine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :magazine_name %>
  </div>

  <div class="field">
    <%= form.label :issue_number %>
    <%= form.number_field :issue_number, id: :magazine_issue_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/magazines/edit.html.erb
<div class="container">
  <h1>Editing Magazine</h1>

  <%= render 'form', magazine: @magazine %>

  <%= link_to 'Show', @magazine %> |
  <%= link_to 'Back', magazines_path %>
</div>

app/views/magazines/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <tr>
    <td><h1>Magazines</h1></td>
    <td><%= link_to 'New Magazine', new_magazine_path, class: 'btn btn-info float-right' %></td>
  </tr>
</table>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Issue number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @magazines.each do |magazine| %>
      <tr>
        <td><%= magazine.name %></td>
        <td><%= magazine.issue_number %></td>
        <td><%= link_to 'Show', magazine %></td>
        <td><%= link_to 'Edit', edit_magazine_path(magazine) %></td>
        <td><%= link_to 'Destroy', magazine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="d-flex justify-content-center">
  <%= will_paginate @magazines, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/magazines/new.html.erb
<div class="container">
  <h1>New Magazine</h1>

  <%= render 'form', magazine: @magazine %>

  <%= link_to 'Back', magazines_path %>
</div>

app/views/magazines/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @magazine.name %>
  </p>

  <p>
    <strong>Issue number:</strong>
    <%= @magazine.issue_number %>
  </p>

  <%= link_to 'Edit', edit_magazine_path(@magazine) %> |
  <%= link_to 'Back', magazines_path %>
</div>