config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/first_task', to: 'welcome#first_task'
  get 'welcome/second_task', to: 'welcome#second_task'
  get 'welcome/third_task', to: 'welcome#third_task'
  get 'welcome/task4', to: 'welcome#task4'
  get 'welcome/task5', to: 'welcome#task5'
  get 'welcome/task6', to: 'welcome#task6'
  get 'welcome/task7', to: 'welcome#task7'
  get 'welcome/task8', to: 'welcome#task8'

  root 'welcome#index'

  resources :orders
  resources :magazines
  resources :authors
  resources :books
  resources :librarians
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def first_task
    sql = "SELECT librarians.name, librarians.surname
           FROM librarians
           WHERE(librarians.id in
           (SELECT orders.librarian_id
           FROM orders
           WHERE orders.price = #{params[:price]}))"
    records_array = ActiveRecord::Base.connection.execute(sql).to_a
    @answer1 = ''
    records_array.each { |arr| arr.each { |a| @answer1 += a + ' ' } }
    p @answer1
    json_response(@answer1)
  end

  def second_task
    sql = "SELECT authors.name
           FROM authors
           WHERE(authors.id in
           (SELECT books.author_id
           FROM books
           WHERE books.genre = '#{params[:genre]}'))"
    records_array = ActiveRecord::Base.connection.execute(sql).to_a
    @answer2 = ''
    records_array.each { |arr| arr.each { |a| @answer2 += a + ' ' } }
    p @answer2
    json_response(@answer2)
  end

  def third_task
    sql = "SELECT authors.name
           FROM authors
           WHERE(authors.id in
           (SELECT books.author_id
           FROM books
           WHERE books.genre != '#{params[:genre]}'))"
    records_array = ActiveRecord::Base.connection.execute(sql).to_a
    @answer3 = ''
    records_array.each { |arr| arr.each { |a| @answer3 += a + ' ' } }
    p @answer3
    json_response(@answer3)
  end

  def task4
    sql = "SELECT authors.name
           FROM authors
           WHERE(authors.id not in
           (SELECT books.author_id
           FROM books
           WHERE books.genre = '#{params[:genre]}'))"
    records_array = ActiveRecord::Base.connection.execute(sql).to_a
    @answer4 = ''
    records_array.each { |arr| arr.each { |a| @answer4 += a + ' ' } }
    p @answer4
    json_response(@answer4)
  end

  def task5
    sql = "SELECT users.name
           FROM users
           WHERE(users.id not in
           (SELECT orders.user_id
           FROM orders
           WHERE orders.price = #{params[:price]}))"
    records_array = ActiveRecord::Base.connection.execute(sql).to_a
    @answer5 = ''
    records_array.each { |arr| arr.each { |a| @answer5 += a + ' ' } }
    p @answer5
    json_response(@answer5)
  end

  def task6
    sql = "SELECT librarians.name
           FROM librarians
           WHERE(librarians.id in
           (SELECT orders.librarian_id
           FROM orders INNER JOIN users on orders.user_id = users.id
           WHERE users.name = '#{params[:name]}'
           GROUP BY orders.librarian_id
           HAVING COUNT(orders.user_id) >= 2))"
    records_array = ActiveRecord::Base.connection.execute(sql).to_a
    @answer6 = ''
    records_array.each { |arr| arr.each { |a| @answer6 += a + ' ' } }
    p @answer6
    json_response(@answer6)
  end

  def task7
    sql = "SELECT COUNT(librarians.name)
           FROM librarians
           WHERE(librarians.id in
           (SELECT orders.librarian_id
           FROM orders INNER JOIN users on orders.user_id = users.id
           WHERE users.name = '#{params[:name]}'
           GROUP BY orders.librarian_id
           HAVING COUNT(orders.user_id) >= 2))"
    records_array = ActiveRecord::Base.connection.execute(sql).to_a
    @answer7 = records_array.first.first
    p @answer7
    json_response(@answer7)
  end

  def task8
    sql = "SELECT lib.surname
           FROM librarians AS lib
           WHERE NOT EXISTS (
              SELECT books.id FROM books
              INNER JOIN books_orders on books_orders.book_id = books.id
              INNER JOIN orders on orders.id = books_orders.order_id
              INNER JOIN librarians on librarians.id = orders.librarian_id
              WHERE librarians.id = lib.id AND books.id NOT IN(
              SELECT books_orders.book_id
              FROM books_orders
              INNER JOIN books on books.id = books_orders.book_id
              WHERE books.name = '#{params[:name]}'
             ))"
    records_array = ActiveRecord::Base.connection.execute(sql).to_a
    @answer6 = ''
    records_array.each { |arr| arr.each { |a| @answer6 += a + ' ' } }
    p @answer8
    json_response(@answer8)
  end

  private

  # Render JSON responce
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container">
  <%= link_to 'Librarians', librarians_path, class: 'btn' %>
  <%= link_to 'Users', users_path, class: 'btn' %>
  <%= link_to 'Books', books_path, class: 'btn' %>
  <%= link_to 'Magazines', magazines_path, class: 'btn' %>
  <%= link_to 'Orders', orders_path, class: 'btn' %>
  <%= link_to 'Authors', authors_path, class: 'btn' %>
  <hr size="30">
</div>
<div class="container">
  <div class="row">
    Знайти прізвища та імена бібліотекарів, що оформили замовлення вартістю n
  </div>
  <div class="row">
    <span>Price:</span>
    <input type="number" id="input1">
    <button id="btn1" class="btn-sm">Find</button>
    <div id="div1"></div>
  </div>

  <div class="row">
    Знайти прізвища авторів, у є книжка заданого жанру
  </div>
  <div class="row">
    <span>Genre:</span>
    <input type="text" id="input2">
    <button id="btn2" class="btn-sm">Find</button>
    <div id="div2"></div>
  </div>

  <div class="row">
    Знайти прізвища авторів, які написали книжки не заданого жанру
  </div>
  <div class="row">
    <span>Genre:</span>
    <input type="text" id="input3">
    <button id="btn3" class="btn-sm">Find</button>
    <div id="div3"></div>
  </div>

  <div class="row">
    Знайти прізвища авторів, які не написали книжки заданого жанру
  </div>
  <div class="row">
    <span>Genre:</span>
    <input type="text" id="input4">
    <button id="btn4" class="btn-sm">Find</button>
    <div id="div4"></div>
  </div>

  <div class="row">
    Знайти прізвища користувачів, які не робили замовлення на n гривень
  </div>
  <div class="row">
    <span>Price:</span>
    <input type="number" id="input5">
    <button id="btn5" class="btn-sm">Find</button>
    <div id="div5"></div>
  </div>

  <div class="row">
    Знайти прізвища бібліотекарів, які видали більше або рівно 2 замовлення людям з даним іменем
  </div>
  <div class="row">
    <span>Name:</span>
    <input type="text" id="input6">
    <button id="btn6" class="btn-sm">Find</button>
    <div id="div6"></div>
  </div>

  <div class="row">
    Знайти кількість бібліотекарів, які видали більше або рівно 2 замовлення людям з даним іменем
  </div>
  <div class="row">
    <span>Name:</span>
    <input type="text" id="input7">
    <button id="btn7" class="btn-sm">Find</button>
    <div id="div7"></div>
  </div>
</div>