config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/first_task', to: 'welcome#first_task'
  get 'welcome/second_task', to: 'welcome#second_task'
  get 'welcome/third_task', to: 'welcome#third_task'
  get 'welcome/task4', to: 'welcome#task4'
  get 'welcome/task5', to: 'welcome#task5'
  get 'welcome/task6', to: 'welcome#task6'
  get 'welcome/task7', to: 'welcome#task7'
  get 'welcome/task8', to: 'welcome#task8'

  root 'welcome#index'

  resources :orders
  resources :magazines
  resources :authors
  resources :books
  resources :librarians
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/librarian.rb
class Librarian < ApplicationRecord
  has_many :orders, dependent: :destroy

  validates :name, :surname, :passport_code, presence: true
end

app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController
  before_action :set_librarian, only: [:show, :edit, :update, :destroy]

  # GET /librarians
  # GET /librarians.json
  def index
    @librarians = Librarian.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /librarians/1
  # GET /librarians/1.json
  def show
  end

  # GET /librarians/new
  def new
    @librarian = Librarian.new
  end

  # GET /librarians/1/edit
  def edit
  end

  # POST /librarians
  # POST /librarians.json
  def create
    @librarian = Librarian.new(librarian_params)

    respond_to do |format|
      if @librarian.save
        format.html { redirect_to @librarian, notice: 'Librarian was successfully created.' }
        format.json { render :show, status: :created, location: @librarian }
      else
        format.html { render :new }
        format.json { render json: @librarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /librarians/1
  # PATCH/PUT /librarians/1.json
  def update
    respond_to do |format|
      if @librarian.update(librarian_params)
        format.html { redirect_to @librarian, notice: 'Librarian was successfully updated.' }
        format.json { render :show, status: :ok, location: @librarian }
      else
        format.html { render :edit }
        format.json { render json: @librarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /librarians/1
  # DELETE /librarians/1.json
  def destroy
    @librarian.destroy
    respond_to do |format|
      format.html { redirect_to librarians_url, notice: 'Librarian was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_librarian
      @librarian = Librarian.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def librarian_params
      params.require(:librarian).permit(:name, :surname, :address, :phone_number, :email, :passport_code)
    end
end

app/helpers/librarians_helper.rb
module LibrariansHelper
end

app/views/librarians/_form.html.erb
<%= form_with(model: librarian, local: true) do |form| %>
  <% if librarian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(librarian.errors.count, "error") %> prohibited this librarian from being saved:</h2>

      <ul>
      <% librarian.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :librarian_name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname, id: :librarian_surname %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :librarian_address %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, id: :librarian_phone_number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :librarian_email %>
  </div>

  <div class="field">
    <%= form.label :passport_code %>
    <%= form.text_field :passport_code, id: :librarian_passport_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/librarians/edit.html.erb
<div class="container">
  <h1>Editing Librarian</h1>

  <%= render 'form', librarian: @librarian %>

  <%= link_to 'Show', @librarian %> |
  <%= link_to 'Back', librarians_path %>
</div>

app/views/librarians/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <tr>
    <td><h1>Librarians</h1></td>
    <td><%= link_to 'New Librarian', new_librarian_path, class: 'btn btn-info float-right' %></td>
  </tr>
</table>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Address</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Passport code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @librarians.each do |librarian| %>
      <tr>
        <td><%= librarian.name %></td>
        <td><%= librarian.surname %></td>
        <td><%= librarian.address %></td>
        <td><%= librarian.phone_number %></td>
        <td><%= librarian.email %></td>
        <td><%= librarian.passport_code %></td>
        <td><%= link_to 'Show', librarian %></td>
        <td><%= link_to 'Edit', edit_librarian_path(librarian) %></td>
        <td><%= link_to 'Destroy', librarian, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="d-flex justify-content-center">
  <%= will_paginate @librarians, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/librarians/new.html.erb
<div class="container">
  <h1>New Librarian</h1>

  <%= render 'form', librarian: @librarian %>

  <%= link_to 'Back', librarians_path %>
</div>

app/views/librarians/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @librarian.name %>
  </p>

  <p>
    <strong>Surname:</strong>
    <%= @librarian.surname %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @librarian.address %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= @librarian.phone_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @librarian.email %>
  </p>

  <p>
    <strong>Passport code:</strong>
    <%= @librarian.passport_code %>
  </p>

  <%= link_to 'Edit', edit_librarian_path(@librarian) %> |
  <%= link_to 'Back', librarians_path %>
</div>